name: CI master
on:
  push:
    branches:
      - 'master'
    tags-ignore:
      - '**'
  workflow_dispatch:
jobs:
  run-tests:
    name: Run tests
    uses: ./.github/workflows/run-tests.yml
    secrets:
      BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
      BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
